---
- hosts: localhost
  gather_facts: false
  vars:
    tower_inventory_file: "/root/ansible-tower-setup-latest/inventory"
    tower_home: "/root/ansible-tower-setup-latest"
    work_station_user: "cloud-user"
    
    
  tasks:
  - name: Fail the play if GUID is not provided
    fail:
      msg: "Please provide the GUID OSP_GUID"
    when: OSP_GUID ==""
  - name: Append inventory file
    blockinfile:
      path: "{{tower_inventory_file}}"
      insertafter: 
      block: |2
        [isolated_group_osp]

        workstation-{{OSP_GUID}}.rhpds.opentlc.com ansible_user={{work_station_user}} ansible_ssh_private_key_file='~/.ssh/openstack.pem' ansible_ssh_common_args='-o StrictHostKeyChecking=no'

        [isolated_group_osp:vars]
        controller=tower



  - name: Run Ansible Tower setup
    shell: "{{tower_home}}/setup.sh"
    async: 3600
    poll: 36


